### ISSUE TITLE
Dynamic Shipping Tax Class Calculation

### ISSUE THREAD

**Issue by jaykobi** [firegento/firegento-magesetup2#70] opened 2017-03-20 10:33 UTC
After reading  a [ticket for firegento-germansetup](https://github.com/firegento/firegento-germansetup/issues/13) (German) I suppose splitting VAT for shipping based on products in cart and their values is not (yet) supported by firegento-magesetup2. 

However, is there a way that only reduced VAT can be used for shippng if there are only reduced-vat-products in the cart?

Currently I can only find one config option (Tax Class for Shipping) to set one tax class that then is used for all carts.

But firegento-magesetup2 creates the product class "Ermäßigtbesteuerter Versand". How to use it?

**Comment by tomekjordan** [comment] 2018-09-26 21:10
Also lookin for this thing. I sell food and we have lower vat rate in Poland 5% or 8% instead of 23%.
it would be great to add support for M2 for tax on shipping

**Comment by aqdennis** [comment] 2019-02-26 10:03
I'm also struggling with this. I used FireGento-MageSetup in my Magento 1.9 webshop with the option to have Dynamics Tax for Shipping.  Now I'm setting up a Magento 2.3 webshop and this option is no longer available?? That is too bad :(

**Comment by sprankhub** [comment] 2020-06-27 15:15
This is a duplicate of https://github.com/firegento/firegento-magesetup2/issues/22.

**Closed by sprankhub** 2020-06-27 15:15 UTC
Labels: enhancement
