### ISSUE TITLE
strange behaviors in delivery_time after reinstall

### ISSUE THREAD

**Issue by latenzio** [firegento/firegento-magesetup2#44] opened 2016-10-07 15:07 UTC
#### the working way:

1) install plain `magento2` and run `setup:install` command
2) install `firegento/magesetup2` and run `setup:upgrade` command
3) --> everything works fine
#### failing from here:

4) run `setup:install` command with `--cleanup-database` option.
5) now you can save `delivery_time` only one time - changes will fail silently

I realized there is a difference in the database now. After step 2) the attributes type is varchar in database. After step 4) its type is text so the values are stored in `catalog_product_entity_text` table but not read correctly it.
#### There are 2 ways to fix that:

1) set type `varchar` in install and update scripts
2) set input `texture` in install and update scripts

I prefer 1). I think most installations will have the `varchar` type in database and its recommended.

Should we also try to move data from the _wrong_ table in this update?
Suggests very welcome.

**Comment by therouv** [comment] 2017-02-04 17:00
@latenzio Unfortunately, I can't reproduce this issue. The attribute type is in both ways always "text".

**Comment by frostblogNet** [comment] 2020-03-20 08:45
We will close this issue from 2016. Feel free to reopen if it is relevant.

Thanks

**Closed by frostblogNet** 2020-03-20 08:45 UTC
