### ISSUE TITLE
Version 2.0.1 breaks your shop

### ISSUE THREAD

**Issue by bjoern-quast** [firegento/firegento-magesetup2#28] opened 2016-07-06 10:06 UTC
Reliance on the attribute field 'is_visible_on_checkout' breaks the shop.
The "UpgradeSchema" is missing, thus an update leads to the mentioned problem. Only a fresh install will work.
Also, please consider using tags or releases that can be used with composer.

**Comment by tecjam** [comment] 2016-07-13 11:45
I can confirm this as it has just happened to me. Products are no longer added to the cart and the exception log states:

`CRITICAL: exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'is_visible_on_checkout' in 'where clause'' in /vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:228`

```
Exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'is_visible_on_checkout' in 'where clause', query was: SELECT COUNT(DISTINCT main_table.attribute_id) FROM `eav_attribute` AS `main_table`
 INNER JOIN `eav_entity_type` AS `entity_type` ON main_table.entity_type_id = entity_type.entity_type_id
 LEFT JOIN `eav_entity_attribute` ON main_table.attribute_id = eav_entity_attribute.attribute_id
 INNER JOIN `catalog_eav_attribute` AS `additional_table` ON main_table.attribute_id = additional_table.attribute_id WHERE (`entity_type_code` = 'catalog_product') AND (`is_visible_on_checkout` = 1)' in /vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:235


```

**Comment by tecjam** [comment] 2016-07-13 12:48
Another fix seems to be: 

`ALTER TABLE `catalog_eav_attribute` ADD `is_visible_on_checkout` SMALLINT(5) NULL COMMENT 'Is Visible On Checkout' AFTER `is_filterable_in_grid` `

**Comment by therouv** [comment] 2016-07-14 19:40
Hi @bjoern-quast @tecjam the issue should be resolved now. Can you please check?

**Comment by frostblogNet** [comment] 2020-03-20 08:42
We will close this issue from 2016. Feel free to reopen if it is relevant.

Thanks

**Closed by frostblogNet** 2020-03-20 08:42 UTC
