### ISSUE TITLE
Problem bei Gruppenprodukt mit Steueranzeige

### ISSUE THREAD

**Issue by 22markets** [firegento/firegento-magesetup2#157] opened 2020-05-22 11:42 UTC
### General

* Module version: 0.2.0
* Magento version: 2.3.5-p1
* PHP version: 7.3

### Issue description

Hello, I have installed firegento master magesetup and created a groupped  product. There you can see that the Tax shown in the Product Group is 0 $ Tax. But the single product has the 19% Tax. 

### Steps to reproduce
http://dev.drechselnundmehr.de/catalog/product/view/id/3677/s/drehkugelschreiberbausaetze-mistral/category/25/

**Comment by sprankhub** [comment] 2020-05-24 21:17
That sounds strange, because in https://github.com/firegento/firegento-magesetup2/issues/150#issuecomment-575025474, this looks good. @grossmann could you check if you can reproduce the issue?

**Comment by jccemden** [comment] 2020-06-04 05:14
Same problem here. Pls fix it!

**Comment by grossmann** [comment] 2020-06-04 11:16
Problem is that the patch is not yet included in the latest version (v. 0.2.0) you have to check out the dev-develpment (not dev-master) branch (with git or composer) to get the fix.
@sprankhub Maybe you can release a new version which includes the fix?

**Comment by 22markets** [comment] 2020-06-04 11:37
That do not change anything

http://dev.drechselnundmehr.de/catalog/product/view/id/3740/s/klick-kugelschreiberbausaetze-tempest/category/25/

composer require firegento/magesetup2:dev-develop

**Comment by 22markets** [comment] 2020-06-04 11:39
I have tested it in different installations with migrated products and wit new created products. In all shops I see 0%

**Comment by jccemden** [comment] 2020-06-04 11:51
Our client sells only products with 19% tax, so we have edited the german translation file:
app/code/FireGento/MageSetup/i18n/de_DE.csv
from: 
"Incl. %1 VAT","Inkl. %1 MwSt."
to: 
"Incl. %1 VAT","Inkl. 19% MwSt."

It's not the best solution, but it works for now.

**Comment by grossmann** [comment] 2020-06-04 12:03
OK, I think we have two separate issues here. The one I reported was the additional tax display on the grouped product (not the child products), see issue #150.
The issue of @22markets is that on the child products he get 0% instead of 7%/19%. I am not sure what the problem here is.
I tested on a M2.3.4-p2 an dev-develop and have correct Tax % displayed.
![grafik](https://user-images.githubusercontent.com/1866724/83754344-1eb3cc80-a66c-11ea-94c0-632c6f2d1a21.png)

**Comment by 22markets** [comment] 2020-06-04 12:16
Hello again :-)

https://www.bbquh.de/test-group

here is a newly created product with a fresh install of magento 2.3.5 with the same behavior. I have tried to find the problem but it has nothing to do with the setting.

**Comment by frostblogNet** [comment] 2020-06-27 09:28
@22markets 

Hello looks like you have an Issue with your tax configuration. I have setup a demo shop with magento sample data and it work like it should.

![grafik](https://user-images.githubusercontent.com/19548641/85919119-c76adb80-b868-11ea-850d-c0f578ace979.png)

I will close this issue for now. If you fine out more feel free to reopen it again.

**Closed** 2020-06-27 09:30 UTC
