### ISSUE TITLE
price details block is shown twice on detail page of configurable product

### ISSUE THREAD

**Issue by roman204** [firegento/firegento-magesetup2#87] opened 2017-10-28 17:08 UTC
### General

* Module version: x.x.x
* Magento version: 2.2.0
* PHP version: 7.X

### Issue description

first time the price-details block is shown at the price which is correct
but the second time it is shown after the tier-price container

### Steps to reproduce

1. create a configurable product
2. open the created product on frontend
![image](https://user-images.githubusercontent.com/584168/32136727-3f83472e-bc13-11e7-8914-aa715595413a.png)

**Comment by dakira** [comment] 2017-12-07 12:24
So I have this exact issue, what can I do to prevent it?

**Comment by dakira** [comment] 2017-12-08 09:31
After applying the fix, I still see the doubled tax information for a second until it gets removed by javascript. This feels like a workaround. The tax information shouldn't be doubled in the first place.

**Comment by dakira** [comment] 2017-12-15 19:26
@mautz-et-tong please re-open. This still happens. See above. It should be fixed at root (i.e. the code that inserts the tax block).

**Comment by hubertus2017** [comment] 2018-01-23 14:23
Hello,
it seems that my firegento version has already the fix built-in. But it shows the tax block twice. For each configuration i have a separate price. I use the new "text swatches" attributes.

**Comment by dakira** [comment] 2018-01-24 00:24
@hubertus2017 this fix only removes the doubled taxes (by javascript) after the fact and only in a specific instance. I guess swatches are not covered. We need a real fix. ;)

**Comment by kemexyz** [comment] 2018-02-06 16:24
I can reproduce this in 2.1.4

![screen shot 2018-02-06 at 17 22 50](https://user-images.githubusercontent.com/22369242/35870633-6adb5c56-0b62-11e8-9987-bdf2133943d7.png)

And it looks like its coming from tier prices, at least from the HTML side of things.

**Comment by luebke** [comment] 2018-11-16 13:13
Here is a quick css fix for that issue.

`.product-info-main {

  & .price-details {
    display: none;
  }

  & .product-info-price {
    & .price-details {
      display: block;
    }
  }

}`

**Comment by sprankhub** [comment] 2020-06-27 12:54
![image](https://user-images.githubusercontent.com/930199/85922758-15420c80-b886-11ea-805f-2f7c053eafca.png)

For a configurable product with tier prices, we indeed still show the price details twice.

**Closed** 2020-06-27 16:37 UTC
