### ISSUE TITLE
Registry key "isSecureArea" already exists

### ISSUE THREAD

**Issue by SimonGSGmbH** [firegento/firegento-magesetup2#158] opened 2020-06-19 20:02 UTC
In Registry.php line 60:
  Registry key "isSecureArea" already exists
magesetup:setup:run <country> [<processors>...]

Kommt direkt nach dem Versuch des Setups...

Magento 2.3.5-p1

**Comment by frostblogNet** [comment] 2020-06-27 09:34
Hello @SimonGSGmbH 

Thanks for you information here. Sadly I was unable to reproduce your issue. 

I will close this issue for now. If you have more information feel free to reopen it agian.

**Comment by tdachev** [comment] 2020-09-21 13:36
The Problem still exists on Magento ver. 2.3.5-p2

**Comment by sprankhub** [comment] 2020-09-21 14:33
@tdachev then... Could you add clear steps to reproduce? Happy to reopen then. However, we were unable to reproduce last time we tried.

**Comment by sprippen** [comment] 2020-10-16 15:42
The Problem still exists on Magento ver. 2.3.5

This error happens to the command

php bin/magento magesetup:setup:run it

In Registry.php line 60:
                                              
  Registry key "isSecureArea" already exists
                                              
magesetup: setup: run <country> [<processors> ...]

**Comment by sprippen** [comment] 2020-10-16 16:27
Same website but with outdated magento, so to version 2.3.3, the problem is not present

**Comment by sprankhub** [comment] 2020-10-20 12:26
Hmm we could not reproduce this locally, but probably, because we did not use HTTPS. @SimonGSGmbH @tdachev @sprippen, could you confirm that you had this issue on an HTTPS-page?

**Comment by SimonGSGmbH** [comment] 2020-10-20 14:09
Server is PHP 7.3.23 on nginx including HTTPS

**Closed** 2020-10-30 08:24 UTC
