### ISSUE TITLE
Error on catalog search page

### ISSUE THREAD

**Issue by matin73** [firegento/firegento-magesetup2#95] opened 2017-11-14 10:42 UTC
### General

Magento 2.2.1
PHP 7.0.25
MySql 5.7

### Issue description

Using catalog search occures error
### Steps to reproduce

Install firegento magesetup. go to shop. enter search-word 

1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'update': This element is not expected. Expected is one of ( attribute, block, referenceBlock, referenceContainer, container, move, uiComponent ).
Line: 822

Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'update': This element is not expected. Expected is one of ( attribute, block, referenceBlock, referenceContainer, container, move, uiComponent ).
Line: 822

#0 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/framework/Config/Dom.php(115): Magento\Framework\Config\Dom->_initDom('<layout xmlns:x...')
#1 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Magento\Framework\Config\Dom->__construct('<layout xmlns:x...', Object(Magento\Framework\App\Arguments\ValidationState), Array, NULL, '/var/www/vhosts...', '%message%\nLine:...')
#2 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#3 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...', Array)
#4 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/framework/Config/DomFactory.php(42): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array)
#5 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/framework/View/Model/Layout/Update/Validator.php(125): Magento\Framework\Config\DomFactory->createDom(Array)
#6 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/framework/View/Model/Layout/Merge.php(461): Magento\Framework\View\Model\Layout\Update\Validator->isValid('<layout xmlns:x...', 'layout_merged', false)
#7 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/framework/View/Model/Layout/Merge.php(442): Magento\Framework\View\Model\Layout\Merge->_validateMergedLayout('LAYOUT_frontend...', '<head>\n   <css ...')
#8 /var/www/vhosts/xxxxxx.at/httpdocs/generated/code/Magento/Framework/View/Model/Layout/Merge/Interceptor.php(193): Magento\Framework\View\Model\Layout\Merge->load(Array)
#9 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/framework/View/Layout/Builder.php(86): Magento\Framework\View\Model\Layout\Merge\Interceptor->load()
#10 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/framework/View/Layout/Builder.php(63): Magento\Framework\View\Layout\Builder->loadLayoutUpdates()
#11 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/framework/View/Page/Config.php(197): Magento\Framework\View\Layout\Builder->build()
#12 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/framework/View/Page/Config.php(207): Magento\Framework\View\Page\Config->build()
#13 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/framework/App/View.php(170): Magento\Framework\View\Page\Config->publicBuild()
#14 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/framework/App/View.php(114): Magento\Framework\App\View->loadLayoutUpdates()
#15 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/module-catalog-search/Controller/Result/Index.php(91): Magento\Framework\App\View->loadLayout()
#16 /var/www/vhosts/xxxxxx.at/httpdocs/generated/code/Magento/CatalogSearch/Controller/Result/Index/Interceptor.php(24): Magento\CatalogSearch\Controller\Result\Index->execute()
#17 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/framework/App/Action/Action.php(107): Magento\CatalogSearch\Controller\Result\Index\Interceptor->execute()
#18 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#19 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callParent('dispatch', Array)
#20 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\CatalogSearch\Controller\Result\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#21 /var/www/vhosts/xxxxxx.at/httpdocs/generated/code/Magento/CatalogSearch/Controller/Result/Index/Interceptor.php(39): Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#22 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/framework/App/FrontController.php(55): Magento\CatalogSearch\Controller\Result\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#23 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#24 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#25 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#26 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#27 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#28 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /var/www/vhosts/xxxxxx.at/httpdocs/app/code/Infortis/Cgen/Plugin/Magento/Framework/App/FrontController.php(32): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#30 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/framework/Interception/Interceptor.php(135): Infortis\Cgen\Plugin\Magento\Framework\App\FrontController->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#31 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#32 /var/www/vhosts/xxxxxx.at/httpdocs/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#33 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#34 /var/www/vhosts/xxxxxx.at/httpdocs/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#35 /var/www/vhosts/xxxxxx.at/httpdocs/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#36 {main}

**Comment by matin73** [comment] 2017-11-14 10:52
error is caused by catalogsearch_result_index.xml

<update handle="catalog_delivery_info"/>

**Comment by Kipperlenny** [comment] 2017-11-17 10:09
duplicate of #92 (and fixed in that ticket too)

**Comment by mautz-et-tong** [comment] 2017-11-17 16:30
Fixed by PR 94

**Closed by mautz-et-tong** 2017-11-17 16:30 UTC
